### ISSUE TITLE
How to use already  already trained weights with ckpt files to do some more iterations? 

### ISSUE THREAD

**Issue by shamanez** [Conchylicultor/DeepQA#107]
I am thinking of fine tuning already trained weights. But when I run main.py it doesn't load previous ckpt files. Is that possible ?

**Comment by Conchylicultor** [comment]
If you use the model is in the right save/model folder, there should be no problem, as for the pretrained model. It is the same command than for predicting but without the `--test` flag

**Comment by shamanez** [comment]
First I downloaded the pretrain module. Then save in insode the save-model folder. But when I run my training it again start from the 1st epoch. May be it's just what it's printing? Um asking if the trained module has a 15 000th checkpoint in it and I continue training I am starting with 15001 right ?

**Comment by shamanez** [comment]
**self.managePreviousModel(self.sess)** This function is to load previous variables and **trained**  word embedding to the model ?

**Comment by Conchylicultor** [comment]
If you see something like `Warning: restoring model from ...`, the model is correctly restored. The epoch number is not saved so starts from one every time the program runs.

**Comment by shamanez** [comment]
Yeah went through it. Just a suggestion, can you please change the code by adding global step to the saver function in order have a check point with the iteration number . I think that would be great.

**Comment by Conchylicultor** [comment]
The iteration number is already saved in the `config.ini` file.
