### ISSUE TITLE
Keras Port?

### ISSUE THREAD

**Issue by PDLBDeveloper** [Conchylicultor/DeepQA#112]
Hi!

I really love DeepQA. You can learn a lot from this fine piece of code. Thanks for sharing!

I wonder, did you consider porting it to Keras?

Best

**Comment by Conchylicultor** [comment]
Keras is a high level library. While it would probably be possible to adapt some part of the code to support Keras, I prefer keeping the low level control that TensorFlow offer. I don't think Keras would add anything useful to this program.
