### ISSUE TITLE
Error running main.py

### ISSUE THREAD

**Issue by ThomasKoscheck** [Conchylicultor/DeepQA#115]
When I want to run main.py it gives me the follwing error.

> python main.py --test
> Traceback (most recent call last):
>   File "main.py", line 24, in <module>
>     from chatbot import chatbot
>   File "/var/www/telegrambot/learningai/DeepQA/chatbot/chatbot.py", line 469
>     print('WARNING: ', end='')
>  ..............................................^
> SyntaxError: invalid syntax

Any ideas? I didnt changed the sourcecode.

Thanks

**Comment by Conchylicultor** [comment]
I think you're​ using Python 2 instead of 3.
