### ISSUE TITLE
Resource 'tokenizers/punkt/PY3/english.pickle' not found.

### ISSUE THREAD

**Issue by AmolMavuduru** [Conchylicultor/DeepQA#117]
I get this error when running main.py: Resource 'tokenizers/punkt/PY3/english.pickle' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()

I have installed nltk but don't know why this is happening.

**Comment by Conchylicultor** [comment]
Did you try `python3 -m nltk.downloader punkt` as the README explains ?
