### ISSUE TITLE
Will training start a custom word embedding?

### ISSUE THREAD

**Issue by Edward-liang** [Conchylicultor/DeepQA#118]
@Conchylicultor 
Hi Dear PO,
Now I want to train without the default Google News Embedding. 
I started the trainning progress with 
`python main.py --test  --modelTag movie_model --corpus lightweight --datasetTag dgk_shooter_z`
,and I noticed in the "save/model/movie_model/param.ini", it says
```
initembeddings = False
embeddingsize = 64
embeddingsource = GoogleNews-vectors-negative300.bin
```
And I am wondering if my training process was with default Google News Embedding?
Because I do not manually set initembeddings with **FALSE**, I am not sure about it.

Thank you for your attention.

**Comment by Conchylicultor** [comment]
If you don't set `--embeddingsource`, it won't use any pre-trained embedding. The embeddingsource is only used if `--embeddingsource` is set.
