### ISSUE TITLE
Wondering about the "daemon" mode in --test

### ISSUE THREAD

**Issue by artmusic0** [Conchylicultor/DeepQA#121]
Recently I'm using DeepQA to train my own dataset. Thanks to this git that makes my graduated work getting much more easy. But, I'm confused how to call DeepQA to directly predict an Ans to only one Question? Seems that in "daemon" mode gives hint, still I can't get any idea to success.
Wish to get some suggestion or advice. Thanks a lot. :)

**Comment by Conchylicultor** [comment]
You have to launch the chatbot in daemon mode and then call the .daemonPredict method.

Have a look at chatbotmanager.py for an example:

https://github.com/Conchylicultor/DeepQA/blob/master/chatbot_website/chatbot_interface/chatbotmanager.py

**Comment by artmusic0** [comment]
Thanks! By the way, is there any method to train small talks ? I'm using my own dataset and met the issue below.
----------------------------------------------------- 
![image](https://cloud.githubusercontent.com/assets/11460852/26769099/231cc78e-49e7-11e7-95f6-7f5d524d4895.png)
-----------------------------------------------------
Seems like issue in size of vocab when loadEmbedding. I've also test other complex chatting without this kind of issue.
