### ISSUE TITLE
How to pass the request to external api and return response as answer?

### ISSUE THREAD

**Issue by nggary** [Conchylicultor/DeepQA#152]
If I ask the chatbot: Book the dinner at 7:00pm, assume that I can extract the time and action from the sentence, but how could I pass these data to external function and return response as the answer?

**Comment by bshao001** [comment]
@nggary Embed the rules into the training data. I did something very similar to what you want. For example, I have this training pairs:

Q: Let x = _num1_ , y = _num2_ , how much is y divided by x ? 
A: _func_val_get_number_divide_para1__num2__para2__num1_ 

At the inference time, your software will check if the question matches any pattern you want very roughly, and extract the two numbers, then feed the question to the model, which will make sure (double-check) the question meets the pattern (as long as it outputs something/a token whose string representation starts with _func_val_), you then run the function to generate the output and reply the question.

For details, please check https://github.com/bshao001/ChatLearner.
