### ISSUE TITLE
Not giving proper response in browser

### ISSUE THREAD

**Issue by PoojaPatel05** [Conchylicultor/DeepQA#154]
I have trained data successfully. but still in the browser when I type hi. it gives reply "ACCELERATORS COMFORT COMFORT SHAW INSIDE INSIDE LANAI LANAI LANAI BIRTH GRIGORY GRIGORY". what is the problem?

**Comment by PoojaPatel05** [comment]
![qa](https://user-images.githubusercontent.com/32588930/31480559-4f6bfb7e-aed3-11e7-86df-6d3020241383.png)

**Comment by TimidLion** [comment]
@PoojaPatel05 How did you solved this problem? I am suffering from same problem.
