### ISSUE TITLE
Train DeepQA on custom dataset

### ISSUE THREAD

**Issue by kushia** [Conchylicultor/DeepQA#16]
Hi everyone!
I was wondering, if I want to train the model on my own data, how it works ?

What should be the format of my data ?
Let's imagine I got a txt with a conversation between 2 persons, how can I use it to train DeepQA ?

Many thanks to you and for you work!
Have a nice day

**Comment by Conchylicultor** [comment]
I'm glad you like it. For the dataset, have a look at the classes textdata.py and cornelldata.py that's where the data is loaded. You can modify those to load your custom dataset.
Have a look at the forks, some people already did that for CSV file or other formats.

**Comment by kushia** [comment]
Thank you very much for your answer!
I'm checking it, and I'm checking the two .txt (movie_line and movie_conversation), but I don't really understand the format of it.
For example, in movie_line we could have : 
L18721 +++$+++ u189 +++$+++ m12 +++$+++ ROK +++$+++ Negative.
If I'm right 
L18721 correspond to lineID
u189 to characterID (What is it by the way ?)
m12 to movieID
ROK to character
Then the text

But why is there all these informations ?
Same thing for movie_conversation

Because, actually, I would more have a big txt in this sense ->
Toto -> What is the sun ?
Teacher -> The sun is a star
etc...
But, with it, I can't give all the informations than movie_conversation and movie_line are providing..

Thanks again for your help!

**Comment by Conchylicultor** [comment]
That's just the original format from the dataset. I did not choose it. The dataset was designed for multiple purpose task, not specifically sentence prediction so they store some additional metadata.

You don't have to do this. Just load your file and parse it to extract the conversations (list of list of strings, one list per conversation).
Here is an example for inspiration:
https://github.com/markmo/DeepQA/commit/ccd48b541d72a408d1fcbcdbc6ddb01f78aa533b

**Comment by kushia** [comment]
Thanks you!
I'm going to look at it!
Have a nice day!
