### ISSUE TITLE
NameError: name 'random' is not defined

### ISSUE THREAD

**Issue by guotong1988** [Conchylicultor/DeepQA#176]
https://github.com/Conchylicultor/DeepQA/blob/master/chatbot/trainner.py#L46

`value = str(random(valueArg[0], max=valueArg[1]))`

**Comment by guotong1988** [comment]
Do not run `trainner.py` seperately

**Comment by GuilongZh** [comment]
发生了啥？脑子没转过来哈，兄弟，为什么呀。那个random到底是哪儿来的？
