### ISSUE TITLE
Thanks (not an issue)

### ISSUE THREAD

**Issue by kootenpv** [Conchylicultor/DeepQA#20]
Just wanted to thank you for the repo, I built this on top: https://github.com/kootenpv/twitterqa . I hope you find the accreditation enough :) 

The reddit thread is here: https://www.reddit.com/r/Python/comments/5fkpoe/twitter_deepqa_train_a_neural_network_to/

**Comment by Conchylicultor** [comment]
Nice, I'll test it. And thank you for citing me :)
