### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by l769829723** [Conchylicultor/DeepQA#204]
OS: Windows 10
Python: 3.6
Tensorflow: 1.12

Command: python main.py

ran a few seconds when throwing this error.

**Comment by ia2341** [comment]
I had the same error. I believe TQDM is the root cause of this problem. One way to solve is this is to remove all TQDM calls and use print statements instead.

**Comment by l769829723** [comment]
I had fixed this issue, that machine hasn't enough swap space.
Hope help to you.

> I had the same error. I believe TQDM is the root cause of this problem. One way to solve is this is to remove all TQDM calls and use print statements instead.

**Comment by l769829723** [comment]
> I had the same error. I believe TQDM is the root cause of this problem. One way to solve is this is to remove all TQDM calls and use print statements instead.

I had fixed this issue, that machine hasn't enough swap space.  
Hope help to you. :)
