### ISSUE TITLE
AttributeError: 'module' object has no attribute 'isclose' with tf 0.11

### ISSUE THREAD

**Issue by loveJasmine** [Conchylicultor/DeepQA#21]
rzai@rzai00:~/prj/DeepQA$ python3 main.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Welcome to DeepQA v0.1 !

TensorFlow detected: v0.11.0
Training samples not found. Creating dataset...
Extract conversations: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 83097/83097 [01:08<00:00, 1214.74it/s]
Saving dataset...
Loaded: 35019 words, 139979 QA
Model creation...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:02:00.0
Total memory: 7.92GiB
Free memory: 3.68GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x898fb60
I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 1.24GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   Y Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
Initialize variables...
WARNING: No previous model found, starting from clean directory: /home/rzai/prj/DeepQA/save/model
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/home/rzai/prj/DeepQA/chatbot/chatbot.py", line 194, in main
    self.mainTrain(self.sess)
  File "/home/rzai/prj/DeepQA/chatbot/chatbot.py", line 208, in mainTrain
    self.textData.makeLighter(self.args.ratioDataset)  # Limit the number of training samples
  File "/home/rzai/prj/DeepQA/chatbot/textdata.py", line 89, in makeLighter
    if not math.isclose(ratioDataset, 1.0):
AttributeError: 'module' object has no attribute 'isclose'
rzai@rzai00:~/prj/DeepQA$

**Comment by Conchylicultor** [comment]
You're using Python 3.4, I just update the program, it should work now.

**Comment by loveJasmine** [comment]
good job
