### ISSUE TITLE
how to leverage tensorflow serving in Production

### ISSUE THREAD

**Issue by Samurais** [Conchylicultor/DeepQA#22]
# Description
Since tensorflow suggest use tensorflow serving for Production. After reading more about Serving, it need an example for loading vocabularies and word embedding resources.

https://tensorflow.github.io/serving/architecture_overview

Is anyone get more credits with TensorFlow Serving?

**Comment by Conchylicultor** [comment]
I'm not completely sure that I correctly understood your issue. If you want to deploy the model using the C++ API, indeed, you might want to load the vocabulary file from the C++ code. For now, the vocabulary file is written with pickle so the easiest way is probably to convert i in a more portable format like CSV. The only thing you need is a list on pairs (word id, word string)

**Comment by Samurais** [comment]
Thanks, TensorFlow Serving seems to be very complicated, it introduces many conceptions. I would take sometime to investigate how to use it. 

Maybe I can update here later.

**Comment by Conchylicultor** [comment]
I'll close this issue because it seems more related to TF than my program.
