### ISSUE TITLE
New ckpt format name with recent TF

### ISSUE THREAD

**Issue by Samurais** [Conchylicultor/DeepQA#23]
# Description

Train the model following the README, it takes two days to run for 30 epochs. After the program exit gracefully, it said -

![image](https://cloud.githubusercontent.com/assets/3538629/20875255/35901592-baf4-11e6-8f8b-39f11485a24c.png)

In the ```save/``` directory, I get 
![image](https://cloud.githubusercontent.com/assets/3538629/20875276/5f7ca9ba-baf4-11e6-83e0-ad51e770b40f.png)

So these are the trained model.

Then I copy **save/model-201612031626** to **save/model-server**. As later chatbot_website would use this folder as default model.
But it does not works. Running **python manage.py runserver** would clean the folder.

```
Saving dataset...
Loaded: 43462 words, 186544 QA
Model creation...
Initialize variables...
WARNING: No previous model found, but some files found at /Users/hain/chatbot_butterfly/save/model-server. Cleaning...
Removing /Users/hain/chatbot_butterfly/save/model-server/checkpoint
Removing /Users/hain/chatbot_butterfly/save/model-server/events.out.tfevents.1480764302.dagama
Removing /Users/hain/chatbot_butterfly/save/model-server/model.ckpt.data-00000-of-00001
Removing /Users/hain/chatbot_butterfly/save/model-server/model.ckpt.index
Removing /Users/hain/chatbot_butterfly/save/model-server/model.ckpt.meta
Removing /Users/hain/chatbot_butterfly/save/model-server/params.ini
Daemon mode, running in background...
Initializing bot...
```

So, I download the **model-pretrained** data from [Google Drive](https://drive.google.com/file/d/0Bw-phsNSkq23amlSZXVqcm5oVFU/view?usp=sharing).

I copy the extracted data of **model-pretrained** into **save/model-server**. The app run successfully, and I can chat with bot from web interface, which is great.

After comparing my model data and model-pretrained, it has different file names.

### save/model-201612031626 
```
checkpoint  
events.out.tfevents.1480764302.dagama  
model.ckpt.data-00000-of-00001  
model.ckpt.index  
model.ckpt.meta  
params.ini
```

### model-pretrained
```
model.ckpt  
model.ckpt.meta  
model_predictions.txt  
params.ini
```

So I guess **model.ckpt.data-00000-of-00001** should be rename to **model.ckpt**.
But it does not work, instead, **python manage.py runserver** said -

```
W tensorflow/core/framework/op_kernel.cc:968] Data loss: Unable to open table file /Users/hain/chatbot_butterfly/save/model-server/mode
l.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/hain/chatbot_butterfly/save/model-server/model.ckpt: Data loss:
 not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:968] Data loss: Unable to open table file /Users/hain/chatbot_butterfly/save/model-server/mode
l.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Initializing bot...
Welcome to DeepQA v0.1 !

TensorFlow detected: v0.11.0rc1
Loading dataset from /Users/hain/chatbot_butterfly/data/samples/...
Loaded: 35019 words, 139979 QA
Model creation...
Initialize variables...
WARNING: Restoring previous model from /Users/hain/chatbot_butterfly/save/model-server/model.ckpt
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/hain/chatbot_butterfly/save/model-server/model.ckpt: Data loss:
 not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/hain/chatbot_butterfly/save/model-server/model.ckpt: Data loss:
 not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/hain/chatbot_butterfly/save/model-server/model.ckpt: Data loss:
 not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
W tensorflow/core/framework/op_kernel.cc:968] Data loss: Unable to open table file /Users/hain/chatbot_butterfly/save/model-server/mode
l.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```

So, how to get files in **model-pretrained**'s format? Am I missing something?

## Environment

Python - 3.5
TensorFlow - 0.11 rc1

**Comment by Samurais** [comment]
# Related with
https://github.com/tensorflow/models/issues/13

**Comment by Samurais** [comment]
# Results of inspect_checkpoint.py
[Get a suggestion to run inspect_checkpoint.py](http://stackoverflow.com/questions/33759623/tensorflow-how-to-restore-a-previously-saved-model-python)

Output

```
$ python ./lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/utils/inspect_checkpoint.py --file_name=/Users/hain/tmp/model-201612031626/model.ckpt.data-00000-of-00001
WARNING:tensorflow:list_variables (from tensorflow.contrib.learn.python.learn.utils.checkpoints) is deprecated and will be removed after 2016-08-22.
Instructions for updating:
Please use tf.contrib.framework.list_variables instead
W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /Users/hain/tmp/model-201612031626/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Unable to open table file /Users/hain/tmp/model-201612031626/model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
(venv-py3)
```

**Comment by Samurais** [comment]
After double checking TensorFlow's version, when the training is running with 0.12, the model.ckpt is not generated. So, in order to use 0.12, we need to do some migration work.

When falling back to 0.11, everything works well. **model.ckpt** is piped out.

**Comment by zameran** [comment]
So i marked, that *.data-00000-of-00001 file do not renamed to model.ckpt back.
Anyway looks like on prev. versons of tensorflow it is ok.
But on tensorflow 12 - bad things take place.

**Comment by Conchylicultor** [comment]
It seems they did change the ckeckpoint name format in the last version.
In my code, it breaks this line:
https://github.com/Conchylicultor/DeepQA/blob/master/chatbot/chatbot.py#L418

So the models are not detected anymore.

**Comment by Conchylicultor** [comment]
Apparently, TF recently introduced a new checkpoint format (saver V2). A quick fix to use the old format with tf 0.12 is to create the saver with the `write_version` flag:

```
saver = tf.train.Saver(write_version=tf.train.SaverDef.V1)
```

**Comment by Conchylicultor** [comment]
I pushed a temporary fix. Tell me if you still encounter problems but it should works now.

**Comment by jehrodrigues** [comment]
I still can't run with the model.ckpt available on Google Drive. Is there a more current one?

**Comment by Conchylicultor** [comment]
I just updated a quick hack to make the code compatible with the saver V2.

@jehrodrigues I also updated the pre-trained model. Everything should works now.
