### ISSUE TITLE
Is there any slack or gitter room to discuss problems? 

### ISSUE THREAD

**Issue by Samurais** [Conchylicultor/DeepQA#24]
hi, folks

After reading and running the program, it is pretty good. But along the way to enhance this project, do we need a slack or gitter room for sharing and discussions?

[Gitter Room](https://gitter.im/chatbot-pilots/DeepQA?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

If there is none, let us build a gitter room with link above.

**Comment by Conchylicultor** [comment]
I've never used that but that seems to be a good idea.

**Comment by Conchylicultor** [comment]
Thank you for your contribution. I merged #27
