### ISSUE TITLE
Enable to train with more corpus

### ISSUE THREAD

**Issue by Samurais** [Conchylicultor/DeepQA#28]
# Description

Currently, **chatbot/chatbot.py** check the parameters and save **corpus** as **self.args.corpus**, but it is not used when loading corpus.

```
python main.py --corpus snaplingo
```

**loadCorpus** is defined in **textdata.py**.

```
    def loadCorpus(self, dirName):
        """Load/create the conversations data
        Args:
            dirName (str): The directory where to load/save the model
        """
        datasetExist = False
        if os.path.exists(os.path.join(dirName, self.samplesName)):
            datasetExist = True

        if not datasetExist:  # First time we load the database: creating all files
            print('Training samples not found. Creating dataset...')
            # Corpus creation
            cornellData = CornellData(self.corpusDir)
            self.createCorpus(cornellData.getConversations())

            # Saving
            print('Saving dataset...')
            self.saveDataset(dirName)  # Saving tf samples
        else:
            print('Loading dataset from {}...'.format(dirName))
            self.loadDataset(dirName)

        assert self.padToken == 0
```

# Solution

To support more **corpus**, first, fix the **corpusDir**, then self.createCorpus should use each corpus's own processer.

The processer should provide **getConversations** method to get conversations.

**Comment by Samurais** [comment]
# Cornell Corpus
By default, the program use cornell corpus. The original data is saved in **data/cornell**.

In all files the field separator is " +++$+++ "
**movie_lines.txt** stores all the sentences. 
**movie_conversations.txt** organize the sentences as dialogues.

- movie_lines.txt
	- contains the actual text of each utterance
	- fields:
		- lineID
		- characterID (who uttered this phrase)
		- movieID
		- character name
		- text of the utterance

- movie_conversations.txt
	- the structure of the conversations
	- fields
		- characterID of the first character involved in the conversation
		- characterID of the second character involved in the conversation
		- movieID of the movie in which the conversation occurred
		- list of the utterances that make the conversation, in chronological 
			order: ['lineID1','lineID2',�,'lineIDN']
			has to be matched with movie_lines.txt to reconstruct the actual content

Other corpus could use the same format as **cornell**, to make the source codes easier to maintain.

# The Ubuntu Dialogue Corpus
https://github.com/rkadlec/ubuntu-ranking-dataset-creator
Its format is different from Cornell Corpus, it is great because it generates 1 true and 9 distractors.

**Comment by Conchylicultor** [comment]
Have look at #16 . If you want to use your own corpus, the easiest way is to create another class like cornell.py which would load your custom format and then integrate it in textdata.py.

**Comment by Conchylicultor** [comment]
Support has been added for new corpus ( OpenSubtittles with #31 ). Now the `corpus` parameter is used for the dataset name (which was your original issue). Hope that helps.
