### ISSUE TITLE
How to use the pre-trained model to run the server?

### ISSUE THREAD

**Issue by jjdblast** [Conchylicultor/DeepQA#35]
I use Dockerfile to build the whole pipeline, then downloaded the model.ckpt from this [link](https://drive.google.com/file/d/0Bw-phsNSkq23amlSZXVqcm5oVFU/view?usp=sharing), and `mkdir save/model-server` in DeepQA/ , put the model.ckpt in that.

But when I run server in chatbot_website/ with this code `redis-server &`, it returned this error:`redis-server: command not found`.

I also found that when I run `python manage.py runserver`, which automatically search the trainning data in DeepQA\data folder, how can I skip that and simply reproduce with the pre-trained model checkpoint?

**Comment by Conchylicultor** [comment]
If you use Docker, you should not have to manually use the redis command. See instructions [here](https://github.com/Conchylicultor/DeepQA/tree/master/docker).

Your error came from the fact redis is not installed on your system. By using docker-compose, it will automatically link the DeepQA image to Redis image. If your not using Docker, you'll have to manually install redis (there is a link on the README for instructions).
```
docker-compose -f deploy.yml up
```

There may be other error as the model config file was generated by a previous version, but it should be possible to correct that by manually edit the file.

**Comment by jjdblast** [comment]
Thanks! That's help me a lot !
