### ISSUE TITLE
How to get him to support the Chinese?

### ISSUE THREAD

**Issue by bournes** [Conchylicultor/DeepQA#5]
How to get him to support the Chinese?

**Comment by Conchylicultor** [comment]
In order to make it speak Chinese, you'll have to train the network with a Chinese text corpus. Then, I'm not sure how word embedding would work for Chinese but it's probably  1 character = 1 word embedding
Have a look at chatbot/textdata.py, it's the class which create the corpus.

**Comment by bournes** [comment]
thank you.

**Comment by bournes** [comment]
This knowledge is needed in China..

**Comment by bournes** [comment]
Whether you can integrate  https://github.com/fxsjy/jieba

**Comment by Conchylicultor** [comment]
I have no knowledge about Chinese language, so I won't add Chinese support. But the program is open source so feel free to use it for your own version.
