### ISSUE TITLE
tensorflow 1.0 issue

### ISSUE THREAD

**Issue by draugaslt** [Conchylicultor/DeepQA#59]
tensorflow 1.0 "AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'"

**Comment by Conchylicultor** [comment]
Yes, in tf 1.0, the RNN functions have been moved to `tf.contrib.rnn` and `tf.contrib.legacy_seq2seq`. I'll try to migrate the program in the next few days.

**Comment by Conchylicultor** [comment]
That should be done. Let me know if you encounter some issues.
