### ISSUE TITLE
This one might help/inspire

### ISSUE THREAD

**Issue by dimeldo** [Conchylicultor/DeepQA#6]
Hi there,

You might be interested in checking out this Tensorflow implementation and taking insipration at improving your code. https://github.com/Charging-Alot/SpeakEasy-AI

**Comment by Conchylicultor** [comment]
Thank you for sharing. They seem to use a similar architecture that mine. So you know what results do they achieve with their model ?

**Comment by dimeldo** [comment]
No, I don't. But I thought it might help with working on your TODO (improvements) list.

**Comment by Conchylicultor** [comment]
I'll have a look. Thanks. They also implement a system of buckets which could be useful to increase the training speed.
