### ISSUE TITLE
Error of using my own data

### ISSUE THREAD

**Issue by qiazhiyisuan** [Conchylicultor/DeepQA#63]
Hi,
This is really an amazing repo!

I try to use my own data, the format of which is arranged according to the 'readme' file. But it always shows the following error:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 4814: ordinal not in range(128)

Hope you can offer a way to solve this problem!
Thank you!

**Comment by Conchylicultor** [comment]
It seems to be an encoding problem. You're probably not using the Latin alphabet. Maybe by encoding your text file in utf8 will it works?
I'm not an expert in encoding but it seems to be a fairly [common issue](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=unicodedecodeerror:+%27ascii%27+codec+can%27t+decode+byte+python3).

**Comment by Conchylicultor** [comment]
I'm closing the issue because the problem don't seems related to DeepQA code.
