### ISSUE TITLE
Word2vec initialization is giving me error in  em_in = tf.get_variable("embedding") line

### ISSUE THREAD

**Issue by alanbekker** [Conchylicultor/DeepQA#65]
def loadEmbedding(self, sess):
        """ Initialize embeddings with pre-trained word2vec vectors
        Will modify the embedding weights of the current loaded model
        Uses the GoogleNews pre-trained values (path hardcoded)
        """

        # Fetch embedding variables from model
        with tf.variable_scope("embedding_rnn_seq2seq/RNN/EmbeddingWrapper", reuse=True):
            em_in = tf.get_variable("embedding")
        with tf.variable_scope("embedding_rnn_seq2seq/embedding_rnn_decoder", reuse=True):
            em_out = tf.get_variable("embedding")

**Comment by Conchylicultor** [comment]
What is the error message ? It's possible that the embedding are not compatible with the last version of tf.

**Comment by alanbekker** [comment]
Did you know if google released a new word2vec embedding that is compatible with TF1?
From your experience when training on cornell/ubuntu datasets is that critical to initialize the embedding layer with word2vec layer?

Thanks you so much for your help! I really appreciate it!

**Comment by Conchylicultor** [comment]
Can you try to replace

    with tf.variable_scope("embedding_rnn_seq2seq/RNN/EmbeddingWrapper", reuse=True):

with

    with tf.variable_scope("embedding_rnn_seq2seq/rnn/embedding_wrapper", reuse=True):

and tell me if this works ?

**Comment by eschnou** [comment]
@Conchylicultor Your fix is correct, the scope has changed with 1.0. Let me know if you want a pull request.
