### ISSUE TITLE
 Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x7f91f658fba8> with a different variable scope than its first use

### ISSUE THREAD

**Issue by draugaslt** [Conchylicultor/DeepQA#68]
Traceback (most recent call last):
  File "/home/tensorflow-chat/bazel-bin/main.runfiles/__main__/main.py", line 29, in <module>
    chatbot.main()
  File "/home/tensorflow-chat/chatbot/chatbot.py", line 166, in main
    self.model = Model(self.args, self.textData)
  File "/home/tensorflow-chat/chatbot/model.py", line 103, in __init__
    self.buildNetwork()
  File "/home/tensorflow-chat/chatbot/model.py", line 168, in buildNetwork
    feed_previous=bool(self.args.test)  # When we test (self.args.test), we use previous output as next input (feed_previous)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 364, in embedding_rnn_seq2seq
    encoder_cell, encoder_inputs, dtype=dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 197, in static_rnn
    (output, state) = call_cell()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn.py", line 184, in <lambda>
    call_cell = lambda: cell(input_, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 739, in __call__
    return self._cell(embedded, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 802, in __call__
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 588, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 230, in __call__
    with _checked_scope(self, scope or "basic_lstm_cell", reuse=self._reuse):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 72, in _checked_scope
    type(cell).__name__))
ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x7f91f658fba8> with a different variable scope than its first use.  First use of cell was with scope 'embedding_rnn_seq2seq/rnn/multi_rnn_cell/cell_0/basic_lstm_cell', this attempt is with scope 'embedding_rnn_seq2seq/rnn/multi_rnn_cell/cell_1/basic_lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

**Comment by eschnou** [comment]
Can you confirm:

- the tensorflow version you are using 
- the command line parameters
- that you are not attempting to restore a model built with a previous version (remove folder save/model/)

Thx !

**Comment by draugaslt** [comment]
- TF: 1.0
- Command:  bazel-bin/main --corpus lightweight --datasetTag XXX
- save dir was empty

Bazel build file: [BUILD](https://github.com/Conchylicultor/DeepQA/files/811447/BUILD.txt)

Bazel build command: `bazel build --force_python=PY3 --host_force_python=PY3 -c opt main`

**Comment by eschnou** [comment]
Strange. I can't reproduce. I have latest code, TF 1.0.0. Only difference with you is I use Python 3.4 but I don't see how this could make a difference.

However, the error message is clear, it seems something has changed with 1.0 and the solution is proposed at the end of the message:

`If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)])`

This would need to be changed here: 
https://github.com/Conchylicultor/DeepQA/blob/master/chatbot/model.py#L145

**Comment by Conchylicultor** [comment]
Did you try what the error message suggest ?

Replace (
https://github.com/Conchylicultor/DeepQA/blob/master/chatbot/model.py#L145 )

```
encoDecoCell = tf.contrib.rnn.BasicLSTMCell(self.args.hiddenSize, state_is_tuple=True)  # Or GRUCell, LSTMCell(args.hiddenSize)
if not self.args.test:  # TODO: Should use a placeholder instead
    encoDecoCell = tf.contrib.rnn.DropoutWrapper(encoDecoCell, input_keep_prob=1.0, output_keep_prob=self.args.dropout)
encoDecoCell = tf.contrib.rnn.MultiRNNCell([encoDecoCell] * self.args.numLayers, state_is_tuple=True)
```

by

```
def build_rnn_cell():
    encoDecoCell = tf.contrib.rnn.BasicLSTMCell(self.args.hiddenSize, state_is_tuple=True)  # Or GRUCell, LSTMCell(args.hiddenSize)
    if not self.args.test:  # TODO: Should use a placeholder instead
        encoDecoCell = tf.contrib.rnn.DropoutWrapper(encoDecoCell, input_keep_prob=1.0, output_keep_prob=self.args.dropout)
    return encoDecoCell
encoDecoCell = tf.contrib.rnn.MultiRNNCell([build_rnn_cell() for _ in range(self.args.numLayers)], state_is_tuple=True)
```

**Comment by Conchylicultor** [comment]
I updated the program to integrate that change. I tested and it should not break the models trained before.
