### ISSUE TITLE
[Feature] Switch pre-trained embeddings to Fasttext format

### ISSUE THREAD

**Issue by eschnou** [Conchylicultor/DeepQA#69]
Facebook has released pre-trained word embeddings for 90 languages !
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

I'll look into switching the word embedding feature to support to this format, making these available to DeepQA.

**Comment by Conchylicultor** [comment]
Nice. Looks promising

**Comment by julien-c** [comment]
Will watch this space for feedback after you've tried this :)

**Comment by Conchylicultor** [comment]
Merged with #83
