### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by ledor473** [Conchylicultor/DeepQA#7]
Hi,

In the README it's noted that Python 3 is needed, but it's not working with Python 3.4.
I had to upgrade to Python 3.5 because the following method was used:
https://docs.python.org/3/library/math.html#math.isclose

I'm not sure if it's the only method that requires 3.5 tho. 

I'm not sure if you want to support it but if so I can try to make the changes.

Cheers

**Comment by Conchylicultor** [comment]
Thank you for the notice. I corrected the readme to be more precise.

**Comment by loveJasmine** [comment]
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/DeepQA$ git diff
diff --git a/chatbot/textdata.py b/chatbot/textdata.py
index 15a74a7..96a7e2b 100644
--- a/chatbot/textdata.py
+++ b/chatbot/textdata.py
@@ -88,7 +88,7 @@ class TextData:
     def makeLighter(self, ratioDataset):
         """Only keep a small fraction of the dataset, given by the ratio
         """
-        if not math.isclose(ratioDataset, 1.0):
+        if not math.fabs(ratioDataset-1.0) < max(1e-9 * max(math.fabs(ratioDataset),1.0),0):
             self.shuffle()  # Really ?
             print('WARNING: Ratio feature not implemented !!!')
         pass


this diff can support the python3.4
