### ISSUE TITLE
Docker deploy.yml is blocked

### ISSUE THREAD

**Issue by chellem** [Conchylicultor/DeepQA#70]
Hi,
when launching the docker process with deploy.yml, it's stuck at Initializing bot...

Is there any configuration that should be done?

**Comment by Conchylicultor** [comment]
I updated the docker compose files so it can print the python stdout. That should help to debug.

**Comment by Conchylicultor** [comment]
Ok, there was a problem in the volume path. I pushed a fix so it should works now.

It's been a while this issue exist so thank you for reporting it.
