### ISSUE TITLE
How to restrict the vocabulary size

### ISSUE THREAD

**Issue by alanbekker** [Conchylicultor/DeepQA#75]
Any ideas how I can restrict the vocabulary size?
I've currently 500k unique words and I would like to reduce it to 50k..and convert the others to UNK

This will solve all the memory issues described in previous reported issues as well.

Thanks!

**Comment by Conchylicultor** [comment]
I just pushed a fix for that #89 . You can now use `--filterVocab 20` to filter the words which appear less than 20 times.

**Comment by nabihach** [comment]
Thanks for the update @Conchylicultor . Just a comment: it may be more useful if we could specify the maximum vocabulary size ourselves, e.g. `maxVocabSize 15000.` Everything else would be replaced with the unknown token. I'll see if I can create a pull request.
