### ISSUE TITLE
I am getting a memory issue when I try to run this. It say it's from the core tensorflow

### ISSUE THREAD

**Issue by shamanez** [Conchylicultor/DeepQA#76]
"Ran out of memory trying to allocate 68.34MiB.  See logs for memory state."
 tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[512,34991]
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[512,34991]

I am using geforce 920M 2GB graphical processor.

**Comment by Conchylicultor** [comment]
If you don't have enough memory in your system, you should try to reduce the number of parameters (batch size, embedding size, hidden size, sequence length,...).

**Comment by shamanez** [comment]
Oh thanks. I was able to trained it with less number of parameters and hidden nodes.
