### ISSUE TITLE
About using a simple custom conversation format.

### ISSUE THREAD

**Issue by shank7485** [Conchylicultor/DeepQA#79]
As mentioned here [1], we can create our own simple conversation data between 2 people. I created a file called simple_chat.txt and placed it in DeepQA/data/lightweight directory with content:

```
Hello
Hi
How are you?
I am good. How are you?
I am fine as well. How is the work?
work is going on as usual. Thanks for asking.
No problem.
```

Now, when I run 

```
 python3 main.py --corpus lightweight --datasetTag simple_chat --test interactive
```

I do not see any answers from the bot. I get an output of something like:
```
Q: Hello
A:

Q: How are you?
A:
```
Is it because my sample data is small? Or can someone explain if I am doing things correctly. 

[1] -  https://github.com/Conchylicultor/DeepQA/tree/master/data/lightweight

**Comment by Conchylicultor** [comment]
Sorry, there was a bug which make the conversation was not loaded if there was a single one. I just push a fix and tried your text file.

```
Q: Hi
A: How are you?
```

**Comment by Conchylicultor** [comment]
Don't forget to delete the pre-processed data inside `data/sample/`

**Comment by julien-c** [comment]
Oops my mistake sorry

**Comment by shank7485** [comment]
@Conchylicultor Thanks. It works correctly now. 

Also, any suggestions on how to increase sentence length? When I try larger sentences, I get a warning saying:

```
Warning: sentence too long, sorry. Maybe try a simpler sentence.
```

Any suggestions? 

Thanks.

**Comment by Conchylicultor** [comment]
The sentence length is determined by the `--sentenceLength` flag. Increase this parameter if you want to use longer sentences.

**Comment by shank7485** [comment]
@Conchylicultor Thanks. 

I am comparing your Chatbot and the one made here: [1]. In [1], it is sort of rule based bot which learns from the user input by linking response with input and builds its knowledge graph. 

It would be amazing if you 2 had discussions with each other about making better Bots. It would be helpful for the rest of us. :)

[1] - https://github.com/gunthercox/ChatterBot
