### ISSUE TITLE
Using the beam search on the module

### ISSUE THREAD

**Issue by shamanez** [Conchylicultor/DeepQA#80]
Does this module trained in the greedy fashion or does this use beam search to generate output as google does in smart replay?

**Comment by Conchylicultor** [comment]
For now, the program simply compute the most likely output, using argmax at each timestep. That's definitely something which would need to be changed in the future.

**Comment by shamanez** [comment]
If we take 3 outputs with maximum probabilities in each time step we will get set of outputs so how we generate sentences with them ?

**Comment by Conchylicultor** [comment]
See this issue #34 which already describe ways to generate the N-bests matches.

I'll close this one as it seems to be a duplicate.
