### ISSUE TITLE
It gives me weird Answers

### ISSUE THREAD

**Issue by paratata** [Conchylicultor/DeepQA#81]
Hello, i trained the model also i used the pretrained model and I still get funny answers as describe what could be the cause.
I'm running tensorflow 1.0 on a mac and Python 3.6

""Q: how are you
A: Dunaway dunaway dunaway persona persona wingspan wingspan sagittarians sagittarians were were were

Q: what is morality
A: Dunaway dunaway bug-wit bug-wit boccia boccia sagittarians sagittarians sagittarians sagittarians sagittarians melvins

Q: I play tennis. What do I play?
A: Voyeur voyeur voyeur voyeur telescopic telescopic telescopic telescopic telescopic telescopic telescopic tenses

Q: hi
A: Dunaway dunaway dunaway stooge please please grove grove grove 95 95 95""

Q: how old are you?
A: Dunaway disappearance fixin fixin fixin fixin fixin sagittarians sagittarians sagittarians sagittarians sagittarians

Q: tell me the alphabet
A: Dunaway dunaway disappearance disappearance disappearance disappearance disappearance disappearance disappearance philistine philistine philistine

**Comment by Conchylicultor** [comment]
From what I understand, it is the pre-trained model which gives those results ?
Can you copy the full output of the program ? That would help to debug. Also try do delete the files in `data/samples/`

**Comment by Edward-liang** [comment]
You happened to meet the same problem I meet before. 
It is caused by not properly feed the pre-trained model.
watch my solution here.

> https://github.com/Conchylicultor/DeepQA/issues/85

**Comment by paratata** [comment]
I deleted the samples files as required @Conchylicultor but it doesnt work and I dont understand the solution @Edward-liang is saying that he has, I move the pretrained fine in the different folders without success.

**Comment by paratata** [comment]
python main.py --test interactive
Welcome to DeepQA v0.1 !

TensorFlow detected: v1.0.0
Loading dataset from /Users/Documents/Machine Learning/DeepQA/data/samples/...
Loaded cornell: 34991 words, 139979 QA
Model creation...
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Initialize variables...
WARNING: No previous model found, starting from clean directory: /Users/Documents/Machine Learning/DeepQA/save/model
Testing: Launch interactive mode:

Welcome to the interactive mode, here you can ask to Deep Q&A the sentence you want. Don't have high expectation. Type 'exit' or just press ENTER to quit the program. Have fun.
Q: hello
A: Actually actually perdido perdido perdido perdido perdido frau frau fairlane fairlane fairlane

Q: ^CTraceback (most recent call last):
  File "main.py", line 29, in <module>
    chatbot.main()
  File "/Users/Documents/Machine Learning/DeepQA/chatbot/chatbot.py", line 202, in main
    self.mainTestInteractive(self.sess)
  File "/Users/Documents/Machine Learning/DeepQA/chatbot/chatbot.py", line 326, in mainTestInteractive
    question = input(self.SENTENCES_PREFIX[0])
KeyboardInterrupt

**Comment by Conchylicultor** [comment]
From your output, the program cannot find the model:

```
WARNING: No previous model found, starting from clean directory: /Users/Documents/Machine Learning/DeepQA/save/model
```

You have to make sure you use the `--modelTag pretrainedv2` flag and that your model is inside `DeepQA/save/model-pretrainedv2/model.ckpt`.

**Comment by Edward-liang** [comment]
Hi @paratata , the problem is maybe the way you name your folder.
In the program, the name is specified as "model-pretrainedv2", however you use "model" in your situation.
