### ISSUE TITLE
How many epoches are used for pre-trained model?

### ISSUE THREAD

**Issue by hanfeisun** [Conchylicultor/DeepQA#82]
I use maxLength=10 and epoch=10 to train on Cornell dataset, and the result seems to be bad.

Can I know how many epoches are used for pre-trained model?

**Comment by Conchylicultor** [comment]
You can see the number of training steps for which the model has been trained by looking at the `config.ini` file.

**Comment by nabihach** [comment]
@Conchylicultor  I think you mean the `params.ini` file, not the `config.ini` file.

In `params.ini`, I see the following information:

```
[General]
version = 0.4
globstep = 32000
maxlength = 10
watsonmode = False
autoencode = False
corpus = cornell
datasettag = 

[Network]
hiddensize = 512
numlayers = 2
embeddingsize = 64
initembeddings = False
softmaxsamples = 0

[Training (won't be restored)]
learningrate = 0.002
batchsize = 256

```

I presume `globstep` here means the number of epochs. Is that correct?

Could you also please tell us how long it took you to train this model? Thanks.

**Comment by Conchylicultor** [comment]
The network as been trained during 32000 iterations with batch size of 256. There was 139979 samples in the dataset so if I'm not mistaken:

```
32000*256/139979 = 58 epochs
```

The training time greatly depends of your hardware. In this case from what I remembered, it took a few hours to train it.

**Comment by nabihach** [comment]
Thanks. One more question: the Cornell dataset contains ~300K utterances in total. Did you randomly sample 139979 of these?

**Comment by nabihach** [comment]
Oh never mind. I just realized it's because you only consider the QnA pairs that have length up to `maxLength`. Thanks!
