### ISSUE TITLE
test - custom data

### ISSUE THREAD

**Issue by y0d4a** [Conchylicultor/DeepQA#84]
Hello, 
how i can tell DeepQA to learn from custom file (test folder in data) ?
i try with main.py --corpus test
but:
error: argument --corpus: invalid choice: 'test' (choose from 'cornell', 'opensubs', 'scotus', 'ubuntu', 'lightweight')

i am experimenting with https://www.clarin.si/repository/xmlui/handle/11356/1063

tnx.

**Comment by Conchylicultor** [comment]
You should follow those instructions: https://github.com/Conchylicultor/DeepQA/tree/master/data/lightweight

As explained, you have to use the flags `--corpus lightweight --datasetTag <name>`
