### ISSUE TITLE
About the sequence_loss function that used in the model.py file

### ISSUE THREAD

**Issue by shamanez** [Conchylicultor/DeepQA#86]
There are two **_sequence_loss_** functions one in the **tf.contrib.legacy_seq2seq.sequence_loss** and other one in the **tf.contrib.seq2seq.sequence_loss**. What is the difference ?

**Comment by Conchylicultor** [comment]
* `tf.contrib.legacy_seq2seq`: is the old seq2seq API, used by tf 0.12 and prior. It's keeped for backward compatibilities
* `tf.contrib.seq2seq`: is the new seq2seq API. Used from tf 1.0
